// export const randomDataPoint: MainMaster = {
//     id: '12345',
//     projectId: 'PROJ001',
//     MC_NO: 'MC001',
//     MC_NAME: 'Machine Alpha',
//     MC_EPC: 'EPC001',
//     CC_NO: 'CC001',
//     CC_NAME: 'Container Beta',
//     CC_EPCNO: 'CEPC001',
//     PACK_NO: 1,
//     PACK_NAME: 'Package Gamma',
//     PACK_EPC: 'PEPC001',
//     PACK_BATCHNO: 'BATCH001',
//     PACK_EXPIRY: new Date('2023-12-31'),
//     TRAY_NO: 'TRAY001',
//     SKU_CODE: 'SKU001',
//     SKU_NAME: 'Product Delta',
//     SKU_QTY: 100,
//     SKU_BATCH: 'SKUBATCH001',
//     BATCH_EXPIRY: new Date('2023-12-31'),
//     PACK_CODE: 'PC001',
//     STATUS: 'Active',
//     UNIT: 'Unit A',
//   };
